apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
  namespace: sample-nginx
  labels:
    app: sample-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  selector:
    app: sample-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP